# Meta Data for SEO

## Homepage
name = "TTSReader 🔊"
title = "🔊 TTS (Text to Speech) Reader Online"
titleSeparator = "|"
description = "Listen to ANY textual content with this AI Text To Speech Reader. Type or upload any text, file, website & book for listening online, proofreading, reading-along or generating professional mp3 voice-overs."


## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["tile_1024x512.jpeg"]
ogLocale = "en"
domainTLD = "ttsreader.com"
titleHome = "TTSReader - Text To Speech Reader & AI Voice-Overs"

## Twitter Cards
twitterSite = "@speechlogger"
twitterCreator = "@speechlogger"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "TTSReader"
schemaAuthor = "Ronen Rabinovici"
schemaAuthorTwitter = "https://twitter.com/speechlogger"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/ronen-r/"
schemaAuthorGitHub = "https://github.com/RonenR"
schemaLocale = "en-US"
schemaLogo = "android-chrome-512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "tile_1024x512.jpeg"
schemaImageWidth = 1024
schemaImageHeight = 512
schemaTwitter = "https://twitter.com/speechlogger"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/ttsreader/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#880015"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "tile_1024x512.jpeg" # put in `./assets/images/`
fillImage = "1024x512 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://ttsreader.com/\">TTSReader Text to Speech</a>"

# Feed
copyRight = "Copyright (c) 2015-2023 Ronen Rabinovici @ WellSource"

# Alert
alert = false
alertDismissible = true
alertText = "Welcome to our new site! Need the previous version? <a class=\"alert-link stretched-link\" href=\"/legacy/\" target=\"_self\">Click here for the legacy version</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/ttsreader/ttsreader-web"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = "ALL" # used in assets/js/index.js, "All" or an array that includes the Types to include in search. Defaults to the docs folder in content.
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = true
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true

[links]
  player = "/player/"
  webPlayer = "https://ttsreader.com/webplayer/?url=https://en.wikipedia.org/wiki/The_Beatles"
  legacy = "/legacy/"
  stories = "/stories/"
  shop = "/shop/"
  upgrade = "/upgrade/"
  export = ""
  commercial = "https://ttsreader.com/blog/2017/05/10/commercial/"
  copyright = "https://ttsreader.com/blog/2017/05/10/copyright/"
  converters = "https://speechnotes.co/converters/"
  speechlogger = "https://speechlogger.com/"
  speechninja = "https://speechninja.co/"
  unreal_studio = "https://app.unrealspeech.com/?ref=ttsreader"
  buttons = "https://buttons-kids.web.app/"
  speechnotes = "https://speechnotes.co/"
  iosApp = "https://apps.apple.com/il/app/simple-text-reader-ttsreader/id1493463248"
  androidApp = "https://play.google.com/store/apps/details?id=com.speechlogger.ttsreader"
  chromeExtension = "https://chrome.google.com/webstore/detail/pakknklefcjdhejnffafpeelofiekebg"
  github = "https://github.com/ttsreader/ttsreader-web"
  issues = "https://github.com/ttsreader/ttsreader-web/issues"
  discussions = "https://github.com/ttsreader/ttsreader-web/discussions"
  feedbackNew = "https://docs.google.com/forms/d/e/1FAIpQLSecnm9ZnFje9S6OSSQqP4Ts4av-hSmhAUbuLvQAojWUdckAtg/viewform?usp=sf_link"
  feedbackLegacy = "https://docs.google.com/forms/d/e/1FAIpQLSdVYIL6UxGrX3VSgJvdrYq2XE0tdCP3BXfScDf5MT4INYXh_w/viewform?usp=sf_link"
  feedbackWebPlayer = "https://docs.google.com/forms/d/e/1FAIpQLSdYGXU2VKVWsJrs8rrqJ9IF9lPlw7Oe3pz01SzMCAWjhluZmg/viewform?usp=sf_link"
  feedbackExtension = "https://docs.google.com/forms/d/e/1FAIpQLSdrXYHPCdhNNEpXgoGZ3aV1_zAPrkjlrQGJURn3jWIvIsIj6g/viewform?usp=sf_link"
  premiumSupportForm = "https://docs.google.com/forms/d/e/1FAIpQLSc-gAEGNiCixhSjTjkJXu3cYSqDJYEMa9vPzRPKnY6Pei_yrQ/viewform?usp=sf_link"
  audioSampleChristopher = "https://ttsreader.com/player/audio/Christopher.mp3"
  audioSampleNoah = "https://ttsreader.com/player/audio/Noah.mp3"
  audioSampleMichelle = "https://ttsreader.com/player/audio/Michelle.mp3"
  audioSampleLily = "https://ttsreader.com/player/audio/Lily.mp3"
  speechify_voiceover = "http://speechify.com/voiceover?via=voiceover"
  murf = "https://get.murf.ai/bz1lyjc4o3nr"
  audioread = "https://audioread.com/?via=ttsreader"
