[[main]]
  name = "Player"
  url = "/player/"
  weight = 10

[[main]]
  name = "Plugin"
  url = "/plugin/"
  weight = 12

[[main]]
  name = "Speech to Text"
  url = "https://speechnotes.co/transcribe/"
  weight = 13

[[main]]
  name = "More"
  weight = 40
  identifier = "tools"

  [[main]]
    name = "Legacy Player"
    weight = 41
    identifier = "legacy"
    url = "/legacy/"
    parent = "tools"

  [[main]]
    name = "Quick Start Guide"
    weight = 42
    identifier = "guide"
    url = "/docs/guides/quick-start-new-player/"
    parent = "tools"

  [[main]]
    name = "Mobile Apps"
    weight = 43
    identifier = "mobile"
    url = "/mobile/"
    parent = "tools"

  [[main]]
    name = "Beep Generator"
    weight = 44
    identifier = "sounds"
    url = "/sounds/"
    parent = "tools"

  [[main]]
    name = "Stories (Books)"
    weight = 46
    identifier = "stories"
    url = "/stories/"
    parent = "tools"

  [[main]]
    name = "SpeechNinja (AAC)"
    weight = 45
    identifier = "portfolio"
    url = "/#portfolio"
    parent = "tools"

  [[main]]
    name = "File converters"
    weight = 47
    identifier = "tools-converters"
    url = "/converters/"
    parent = "tools"

  [[main]]
    name = "Pricing"
    weight = 49
    identifier = "pricing"
    url = "/docs/support/pricing/"
    parent = "tools"

  [[main]]
    name = "Docs"
    weight = 50
    identifier = "docs"
    url = "/docs/"
    parent = "tools"

  [[main]]
    name = "Blog, News & Updates"
    weight = 51
    identifier = "blog"
    url = "/blog/"
    parent = "tools"
  [[main]]
    name = "Contact"
    weight = 52
    identifier = "contact"
    url = "/contact/"
    parent = "tools"
  [[main]]
    name = "Privacy"
    weight = 60
    identifier = "privacy"
    url = "https://ttsreader.com/docs/legal/privacy/"
    parent = "tools"

