[[main]]
  name = "Get Started"
  url = "/player/"
  weight = 10

[[main]]
  name = "Legacy"
  url = "/legacy/"
  weight = 11

[[main]]
  name = "Upgrade"
  url = "/upgrade/"
  weight = 12

[[main]]
  name = "Portfolio"
  url = "/#portfolio"
  weight = 13

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 14
